rabbitmq:
  server: rmq.domain # address of rabbitmq server
  port: 5672 # tcp port of rabbitmq server
  user: svc-user # amqp username
  password: "**********" # amqp password
  exchange: systemExchange # configured exchange for vCD
  queue: sii-lumext
  routing_key: sii-lumext
  use_ssl: true # true/false depending on your rmq server

ldap:
  address: ldaps://---------:636 # ldap address starting with ldap:// or ldaps://
  user: user@domain # username for LDAP administration
  secret: "***********" # password for LDAP administration
  base: dc=domain,dc=tld # LDAP base path to use as a root for OU creation(s)
  domain: domain.tld # name of the LDAP domain
  search_timeout: 5 # seconds
  operation_timeout: 5 # seconds
  cacert_file: /etc/ssl/certs/ca-certificates.crt # If LDAPs is used
  userAccountControl: 66048 # Default mode for user creation:
                            # - (66048: no password expiration + user activated)

log:
  config_path: /opt/sii/lumext/etc/logging.json
